apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tab8m51pl-java-springboot
  janus-idp.io/tekton: tab8m51pl-java-springboot
  backstage.io/kubernetes-id: tab8m51pl-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tab8m51pl-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
